### ISSUE TITLE
Add `MustGet...` functions that return value directly

### ISSUE THREAD

**Issue by takanuva15** [oleiade/reflections#21]
Hi, thanks for making this awesome library. Currently, all the `Get...` functions return a tuple `(value, err)` like the examples the docs show:
```
value, err := reflections.GetField(s, fieldName)
```

Can we please add equivalent `MustGet...` functions that return only `value`, and otherwise panic if there is an error? This would be very useful in situations like tests, where I know that the reflect must pass for the assertion to pass, so there is no need to check the error separately. This would make it easy to cut the unit test size in half since I wouldn't need double the code to write a single assert.

Example:
```
assert.Equal(t, "test", reflections.MustGetField(s, fieldName))
```

(I can raise a PR for this if it that works for you)

**Comment by oleiade** [comment]
Hey @takanuva15 👋🏻 

Sorry for the delay in my reply, I haven't gotten time to get back to you just yet, but I will as soon as I have available 🧠 time 🙇🏻

**Comment by oleiade** [comment]
Hey @takanuva15 👋🏻 

Apologies for the late reply. I've given this some thought, and although I find you've made rather compelling arguments for it, and I appreciate the effort you've put into thinking about it, I'm rather against doing this. 

There are two main reasons for that on my side:
-  in Go, explicit error handling is idiomatic: returning a value and an error is the most common pattern. Even in the case of testing, using a library such as testify means you can effectively assert your code using `require.NoError`, and `assert.Equal(something...)`.
- The vast majority of libraries should not panic. I don't know how controversial that is of a view. Still, as an engineer with more than a decade of experience and having used Go since its first release, I can probably count on my fingers the number of times I had to resort to using or declaring a function that panics. From my perspective, `panic` means and is meant to be used as "the program has encountered an error or problem that keeps it from continuing its execution". I can see how that's useful in a package like deep, or sqlx (if fetching the initial state of my app fails, there's probably something wrong in my configuration, and the program should indeed crash). But reflections are about introspection, and I'd rather not introduce those kinds of panicking primitives. 

That being said, although I'm against the `Must` approach, this opens the whole topic of "is there a way to add or modify reflections" to make it a better or more convenient tool when it comes to testing. I'd be keen to hear any other thoughts you might have in the future in that regards 🙇🏻
